name: riyadh_metro
description: A clean Flutter test project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^0.13.0
mime: ^1.0.0
go_router: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
